// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeklzkthzkdtpqggytwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFla2x6a3RoemtkdHBxZ2d5dHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDc5MTMsImV4cCI6MjA2NTkyMzkxM30.ZWqI-NfPFQHVCTzlYaruhVvvYnKXuFRptZKToFYr2BQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);